DROP TABLE PEDIDO CASCADE CONSTRAINTS;

CREATE TABLE PEDIDO (
NUMERO          NUMBER(6)       NOT NULL,
DATA            DATE            NOT NULL,
PRAZO_ENTREGA   DATE            null,
RUA             varchar2(80)    null,
NR              NUMBER(4)       null,
BAIRRO          varchar2(50)    null,
COMPLEMENTO     varchar2(100)   null,
CIDADE          varchar2(50)    null,
UF              varchar2(2)     null,
CEP             varchar2(10)    null,
TOTAL_FATURA    NUMBER(8,2)     null,
CODIGO_CLI      NUMBER          NOT NULL,
MATRICULA_VEN   NUMBER          NOT NULL
);

DROP TABLE ESTOQUE;

CREATE TABLE ESTOQUE (
DATA_ENTRADA        DATE        NOT NULL,
CODIGO_PRO          NUMBER      NOT NULL,
CODIGO_PRA          NUMBER(3)   NOT NULL,
QUANTIDADE          NUMBER(5)   NOT NULL,
DATA_VALIDADE       DATE        NULL
);

DROP TABLE CAPACIDADE_ESTOQUE;

CREATE TABLE CAPACIDADE_ESTOQUE (
CODIGO_PRO  NUMBER      NOT NULL,
CODIGO_PRA  NUMBER(3)   NOT NULL,
QUANTIDADE  NUMBER(5)   NOT NULL
);

DROP TABLE ITEM_PRODUTO;

CREATE TABLE ITEM_PRODUTO (
CODIGO_PRO    NUMBER NOT NULL,
NUMERO_PED    NUMBER(6) NOT NULL,  
QUANTIDADE    NUMBER(5) NOT NULL,
PRECO_UNITARIO NUMBER(5,2) NOT NULL,
VALOR_ITEM      NUMBER(7,2) NULL
);

ALTER TABLE PEDIDO ADD CONSTRAINT PK_PEDIDO PRIMARY KEY (NUMERO);

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY(CODIGO_CLI) REFERENCES CLIENTE(CODIGO)
ADD CONSTRAINT FK_PEDIDO_VENDEDOR FOREIGN KEY(MATRICULA_VEN) REFERENCES VENDEDOR(MATRICULA);

ALTER TABLE ESTOQUE ADD CONSTRAINT FK_ESTOQUE PRIMARY KEY(DATA_ENTRADA,CODIGO_PRO,CODIGO_PRA);

ALTER TABLE ESTOQUE
ADD CONSTRAINT FK_ESTOQUE_PRODUTO FOREIGN KEY(CODIGO_PRO) REFERENCES PRODUTO(CODIGO)
ADD CONSTRAINT FK_ESTOQUE_PRATELEIRA FOREIGN KEY(CODIGO_PRA) REFERENCES PRATELEIRA(CODIGO);

ALTER TABLE CAPACIDADE_ESTOQUE ADD CONSTRAINT PK_CAPACIDADE_ESTOQUE PRIMARY KEY(CODIGO_PRO,CODIGO_PRA);

ALTER TABLE CAPACIDADE_ESTOQUE
ADD CONSTRAINT FK_CAPACIDADE_PRODUTO FOREIGN KEY(CODIGO_PRO) REFERENCES PRODUTO(CODIGO)
ADD CONSTRAINT FK_CAPACIDADE_PRATELEIRA FOREIGN KEY(CODIGO_PRA) REFERENCES PRATELEIRA(CODIGO);

ALTER TABLE ITEM_PRODUTO ADD CONSTRAINT PK_ITEM_PRODUTO PRIMARY KEY(CODIGO_PRO,NUMERO_PED);

ALTER TABLE ITEM_PRODUTO
ADD CONSTRAINT FK_ITEM_PRODUTO FOREIGN KEY(CODIGO_PRO) REFERENCES PRODUTO(CODIGO)
ADD CONSTRAINT FK_ITEM_PEDIDO FOREIGN KEY(NUMERO_PED) REFERENCES PEDIDO(NUMERO);
