--BD2 - 2o Bim -Atividade de SQL - DDL - Tabelas do Projeto Pedido - Parte 1
DROP TABLE CLIENTE CASCADE CONSTRAINTS;

CREATE TABLE CLIENTE (
CODIGO  NUMBER,
NOME            VARCHAR2(60) NOT NULL,
RUA             VARCHAR2(80) NOT NULL,
NR              NUMBER(4) NOT NULL,
BAIRRO          VARCHAR2(50) NOT NULL,
COMPLEMENTO     VARCHAR2(100) NOT NULL,
CIDADE          VARCHAR2(50) NOT NULL,
UF              VARCHAR2(2) NOT NULL,
CEP             VARCHAR2(10) NOT NULL,
CONSTRAINT PK_CLIENTE PRIMARY KEY (CODIGO)
);

DROP TABLE PF;

CREATE TABLE PF (
CODIGO_CLIENTE_PF   NUMBER,       
CNPF                VARCHAR2(14) NOT NULL,
RG                  VARCHAR2(10) NOT NULL,
DATA_NASCIMENTO     DATE         NOT NULL,
CONSTRAINT PK_PF PRIMARY KEY(CODIGO_CLIENTE_PF)
);

DROP TABLE PJ;

CREATE TABLE PJ (
CODIGO_CLIENTE_PJ   NUMBER,       
CNPJ                VARCHAR2(19) NOT NULL,
IE                  VARCHAR2(10) NOT NULL,
NOME_FANTASIA       VARCHAR2(60) NOT NULL,
CONSTRAINT PK_PJ PRIMARY KEY(CODIGO_CLIENTE_PJ)
);

DROP TABLE PRODUTO CASCADE CONSTRAINTS;

CREATE TABLE PRODUTO (
CODIGO          NUMBER NOT NULL,
DESCRICAO       varchar2(80) NOT NULL,
UNID_MEDIDA     varchar2(10) NOT NULL,
CONSTRAINT PK_PRODUTO PRIMARY KEY(CODIGO)
);

DROP TABLE VENDEDOR CASCADE CONSTRAINTS;

CREATE TABLE VENDEDOR (
MATRICULA       NUMBER NOT NULL,
NOME            varchar2(60) NOT NULL,
CNPF            varchar2(14) NOT NULL,
CONSTRAINT PK_VENDEDOR PRIMARY KEY(MATRICULA)
);

DROP TABLE FONE_CLIENTE;

CREATE TABLE FONE_CLIENTE (
NUMERO              varchar2(14) NOT NULL,
COGIDO_CLIENTE_FONE      NUMBER NOT NULL,
CONSTRAINT PK_FONE_CLIENTE PRIMARY KEY(NUMERO,COGIDO_CLIENTE_FONE)
);

ALTER TABLE FONE_CLIENTE
ADD CONSTRAINT FK_FONE_CLIENTE FOREIGN KEY(COGIDO_CLIENTE_FONE) REFERENCES CLIENTE(CODIGO);

DROP TABLE FONE_VENDEDOR;

CREATE TABLE FONE_VENDEDOR (
NUMERO              varchar2(14) NOT NULL,
MATRICULA_VENDEDOR  NUMBER NOT NULL,
CONSTRAINT PK_FONE_VENDEDOR PRIMARY KEY(NUMERO,MATRICULA_VENDEDOR)
);

ALTER TABLE FONE_VENDEDOR
ADD CONSTRAINT FK_FONE_VENDEDOR FOREIGN KEY(MATRICULA_VENDEDOR) REFERENCES VENDEDOR(MATRICULA);

DROP TABLE PRATELEIRA CASCADE CONSTRAINTS;

CREATE TABLE PRATELEIRA (
CODIGO          NUMBER(3)       NOT NULL,
DESCRICAO       varchar2(50)    NOT NULL,
NUMERO_SECOES   NUMBER(2)       NOT NULL,
CONSTRAINT PK_PRATELEIRA PRIMARY KEY(CODIGO)
);

